### ISSUE TITLE
HTML files simplification

### ISSUE THREAD

**Issue by Hunajpu** [Kweku007/flask-blog#5]
I notice that I would be more convinient if we redesign the html templates(contacts.html, index.html and blog.html) to be based on one base.html file (As I did in project.html) although it is not something crucial. First we should try merging portfolio-page pull request that I just did and see if it has any conflicts. @Kweku007

**Comment by kweku-aboagye** [comment]
Implemented! Would merge this soon

**Comment by Hunajpu** [comment]
Excellent! I think we can close this issue
